# Generated by Django 4.1.7 on 2023-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
