# Generated by Django 4.1.7 on 2023-03-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_category'),
        ('Document', '0002_category_document_document_image'),
    ]

    operations = [
    ]
